export const CORRECT_NUMBERS = '0123456789';
export const CORRECT_LETTERS =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
export const CORRECT_SPEC_SYMBOLS = '_@.';
export const CORRECT_CHARACTERS =
    CORRECT_LETTERS + CORRECT_NUMBERS + CORRECT_SPEC_SYMBOLS;
export const CORRECT_CHARACTERS_OBJ = {
    CORRECT_NUMBERS,
    CORRECT_LETTERS,
    CORRECT_SPEC_SYMBOLS,
};
